### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by fireblastfr** [Charismara/pixelmon-hacks-issues#33] opened 2023-05-01 11:57 UTC
### vvv

A option for Automatic drop all or Take all after killing pokemon gonna be useful when fishing and make auto battle stop when its against a shiny and legendary pokemon

**Comment by Charismara** [comment] 2023-05-01 20:02
duplicate of #25 and #31

**Closed as completed by Charismara** 2023-05-01 20:02 UTC
Labels: duplicate, enhancement
